name: jlab-metadata-service-docs
channels:
  - conda-forge
dependencies:
- python=3.7
- sphinx>=1.8
- sphinx_rtd_theme
- recommonmark
- pip:
  - git+git://github.com/minrk/pytest-check-links@master#egg=pytest-check-links
